import Head from 'next/head'

const Cabecalho = () => {
  return (
    <Head>
      <title>Gearspark Engenharia</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Cabecalho
